
server:
  port: 8088
  servlet:
    context-path: /base

spring:
  application:
    name:  test
  messages:
    basename: messages,messages_sys,messages_mst
    encoding: UTF-8
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      testOnReturn: false
      testWhileIdle: true
      maxActive: 1
      removeAbandoned: true
      removeAbandonedTimeoutMillis: 1
      name: datasource
      testOnBorrow: false
      minIdle: 1
      initialSize: 1
      poolPreparedStatements: true
      url: jdbc:mysql://121.5.73.118:3306/tms?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      validationQuery: select 1
      maxOpenPreparedStatements: 300
      username: root
      password: 'Hsql~112233'

feign:
  hystrix:
    enabled: true

jwt:
  header: Authorization
  expires_in: 3000 # 50 minutes
  secret: base2018cotyso
app:
  name: base